### ISSUE TITLE
wn version

### ISSUE THREAD

**Issue by vzaliva** [johan456789/yaktoa#8]
```
Traceback (most recent call last):
  File "/Users/lord/tmp/yaktoa/main.py", line 116, in <module>
    from pywsd.lesk import simple_lesk
  File "/usr/local/lib/python3.10/site-packages/pywsd/__init__.py", line 14, in <module>
    from wn import WordNet
ImportError: cannot import name 'WordNet' from 'wn' (/usr/local/lib/python3.10/site-packages/wn/__init__.py)
```

Solution:

`pip install -U wn==0.0.23`

**Comment by johan456789** [comment]
In my testing, wn is installed along with pywsd
